-- Catalogo Clientes: a lista curada que vai no link enviado por WhatsApp.
-- Antes isso vivia num CSV + HTML estatico gerado por script; agora mora aqui
-- para poder ser editada pelo /admin/catalogo-clientes sem depender de deploy.

CREATE TABLE IF NOT EXISTS public.catalogo_clientes (
  id            UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  codigo        TEXT NOT NULL UNIQUE,
  nome          TEXT NOT NULL,
  categoria     TEXT NOT NULL,
  categoria_rotulo TEXT,
  subcategoria  TEXT,
  grupo         TEXT,
  grupo_rotulo  TEXT,
  preco         NUMERIC(10,2),
  imagem_url    TEXT,
  imagem_secundaria_url TEXT,
  cores         JSONB NOT NULL DEFAULT '[]'::jsonb,
  destaque      BOOLEAN NOT NULL DEFAULT false,
  ordem         INTEGER NOT NULL DEFAULT 0,
  ativo         BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_catalogo_clientes_ordem ON public.catalogo_clientes(ativo, ordem);
CREATE INDEX IF NOT EXISTS idx_catalogo_clientes_grupo ON public.catalogo_clientes(grupo);

GRANT SELECT ON public.catalogo_clientes TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.catalogo_clientes TO authenticated;
GRANT ALL ON public.catalogo_clientes TO service_role;

ALTER TABLE public.catalogo_clientes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read catalogo clientes" ON public.catalogo_clientes;
CREATE POLICY "Public can read catalogo clientes"
  ON public.catalogo_clientes FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can insert catalogo clientes" ON public.catalogo_clientes;
CREATE POLICY "Admins can insert catalogo clientes"
  ON public.catalogo_clientes FOR INSERT TO authenticated
  WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS "Admins can update catalogo clientes" ON public.catalogo_clientes;
CREATE POLICY "Admins can update catalogo clientes"
  ON public.catalogo_clientes FOR UPDATE TO authenticated
  USING (public.is_admin_user()) WITH CHECK (public.is_admin_user());

DROP POLICY IF EXISTS "Admins can delete catalogo clientes" ON public.catalogo_clientes;
CREATE POLICY "Admins can delete catalogo clientes"
  ON public.catalogo_clientes FOR DELETE TO authenticated
  USING (public.is_admin_user());

CREATE OR REPLACE FUNCTION public.catalogo_clientes_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_catalogo_clientes_updated_at ON public.catalogo_clientes;
CREATE TRIGGER trg_catalogo_clientes_updated_at
  BEFORE UPDATE ON public.catalogo_clientes
  FOR EACH ROW EXECUTE FUNCTION public.catalogo_clientes_set_updated_at();

-- Carga inicial: os 124 produtos ja curados. ON CONFLICT evita duplicar
-- se a migration rodar duas vezes, e preserva o que ja foi editado no admin.
INSERT INTO public.catalogo_clientes
  (codigo, nome, categoria, categoria_rotulo, subcategoria, grupo, grupo_rotulo,
   preco, imagem_url, imagem_secundaria_url, cores, destaque, ordem)
VALUES
  ('14794', 'Garrafa Led Termometro 500 Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas Térmicas / Squeezes', 'garrafas', 'Garrafas', 44.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/14794/14794_1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/14794/14794_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Dourado", "h": "#D4A15A"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, true, 1),
  ('06033', 'Garrafa Quencher 1,2L', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Canecas', 'garrafas', 'Garrafas', 92.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06033-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/06033/06033_2.jpg', '[{"n": "Amarelo Com Azul", "h": ["#EAB308", "#3B82F6"]}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Pink", "h": "#DB2777"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Rosa Claro", "h": "#F9A8D4"}, {"n": "Verde", "h": "#22C55E"}]'::jsonb, true, 2),
  ('01318', 'Mochila Nylon Usb 20L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Mochilas e Sacochilas', 'mochilas', 'Mochilas', 91.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01318-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01318-2-v1.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Preto", "h": "#111827"}]'::jsonb, true, 3),
  ('18921', 'Squeeze Alumínio 600Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas Térmicas / Squeezes', 'garrafas', 'Garrafas', 30.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18921-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18921-2-v1.jpg', '[{"n": "Rosa", "h": "#EC4899"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, true, 4),
  ('18645L', 'Copo Térmico 500Ml *Liso C/ Abridor', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Copos', 'copos-e-canecas', 'Copos e Canecas', 44.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18645L-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/18645l/18645l_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Azul Escuro", "h": "#1E3A5F"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Verde Claro", "h": "#4ADE80"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Vinho", "h": "#7F1D1D"}]'::jsonb, false, 5),
  ('03006A', 'Copo Fibra De Bambu 350Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Copos', 'copos-e-canecas', 'Copos e Canecas', 15.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03006A-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03006A-2-v1.jpg', '[{"n": "Roxo", "h": "#8B5CF6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Bege", "h": "#E8D9BE"}, {"n": "Rosa", "h": "#EC4899"}]'::jsonb, false, 6),
  ('06094', 'Copo Vidro Parede Dupla 80Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Copos', 'copos-e-canecas', 'Copos e Canecas', 18.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06094-1-v1.jpg', NULL, '[{"n": "Transparente", "h": "#E5E7EB"}]'::jsonb, false, 7),
  ('14726L', 'Copo Térmico Inox 320Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Copos', 'copos-e-canecas', 'Copos e Canecas', 42.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/14726L-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/14726L-2-v1.jpg', '[{"n": "Laranja", "h": "#F97316"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}]'::jsonb, false, 8),
  ('14498', 'Copo Fibra De Arroz 350Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Copos', 'copos-e-canecas', 'Copos e Canecas', 7.48, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/14498-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/14498-2-v1.jpg', '[{"n": "Bege", "h": "#E8D9BE"}]'::jsonb, false, 9),
  ('08245', 'Copo Inox Parede Dupla 150Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Copos', 'copos-e-canecas', 'Copos e Canecas', 51.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08245-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08245-2-v1.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Preto", "h": "#111827"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Dourado", "h": "#D4A15A"}, {"n": "Verde", "h": "#22C55E"}]'::jsonb, false, 10),
  ('06096', 'Copo Vidro Parede Dupla 160Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Copos', 'copos-e-canecas', 'Copos e Canecas', 18.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06096-1-v1.jpg', NULL, '[{"n": "Transparente", "h": "#E5E7EB"}]'::jsonb, false, 11),
  ('12487F', 'Squeeze Aluminio Fosco 650Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas Térmicas / Squeezes', 'garrafas', 'Garrafas', 27.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/12487F-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/12487F/12487F_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 12),
  ('9139A', 'Squeeze Aluminio 500Ml C/ Bico E Mosquetão', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas Térmicas / Squeezes', 'garrafas', 'Garrafas', 24.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/9139A-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/9139A-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Marrom", "h": "#92400E"}, {"n": "Rosa", "h": "#EC4899"}]'::jsonb, false, 13),
  ('17012', 'Garrafa Plástica 700Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas Térmicas / Squeezes', 'garrafas', 'Garrafas', 21.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/17012-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/17012-2-v2.jpg', '[{"n": "Laranja", "h": "#F97316"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 14),
  ('02112', 'Garrafa Térmica 400Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas Térmicas / Squeezes', 'garrafas', 'Garrafas', 46.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02112-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02112-2-v1.jpg', '[{"n": "Rosa", "h": "#EC4899"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Preto", "h": "#111827"}, {"n": "Dourado", "h": "#D4A15A"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 15),
  ('18695', 'Garrafa Plástica 600Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas Térmicas / Squeezes', 'garrafas', 'Garrafas', 17.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18695-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/18695/18695_2.jpg', '[{"n": "Azul Claro", "h": "#60A5FA"}, {"n": "Azul Escuro", "h": "#1E3A5F"}, {"n": "Fume", "h": "#9BA3AB"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Transparente", "h": "#E5E7EB"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 16),
  ('09138', 'Squeeze Alumínio 420Ml C/ Mosquetão', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas Térmicas / Squeezes', 'garrafas', 'Garrafas', 19.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/09138-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/09138-2-v1.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Amarelo", "h": "#EAB308"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 17),
  ('18552', 'Garrafa Inox 750Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas de Inox / Alumínio', 'garrafas', 'Garrafas', 39.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18552-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18552-2-v1.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Preto", "h": "#111827"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Prata", "h": "#C0C0C0"}]'::jsonb, false, 18),
  ('17011F', 'Garrafa 750Ml Inox', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas de Inox / Alumínio', 'garrafas', 'Garrafas', 46.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/17011F-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/17011F/17011F_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Preto Com Prata", "h": ["#111827", "#C0C0C0"]}, {"n": "Preto Com Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 19),
  ('18855', 'Garrafa Térmica Inox 850Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas de Inox / Alumínio', 'garrafas', 'Garrafas', 77.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18855-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18855-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Laranja", "h": "#F97316"}]'::jsonb, false, 20),
  ('06012', 'Garrafa Inox Parede Dupla 250Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas de Inox / Alumínio', 'garrafas', 'Garrafas', 47.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06012-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06012-2-v1.jpg', '[{"n": "Cinza", "h": "#6B7280"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 21),
  ('18781', 'Garrafa De Alumínio 600Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas de Inox / Alumínio', 'garrafas', 'Garrafas', 28.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18781-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18781-2-v2.jpg', '[{"n": "Cinza", "h": "#6B7280"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}]'::jsonb, false, 22),
  ('08195', 'Garrafa Térmica Inox 550Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Garrafas de Inox / Alumínio', 'garrafas', 'Garrafas', 69.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08195-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08195-2-v1.jpg', '[{"n": "Rosa", "h": "#EC4899"}, {"n": "Inox", "h": "#B8BCC4"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Bege", "h": "#E8D9BE"}, {"n": "Preto", "h": "#111827"}, {"n": "Amarelo", "h": "#EAB308"}]'::jsonb, false, 23),
  ('07392', 'Caneca Inox 180Ml C/ Tampa', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Canecas', 'copos-e-canecas', 'Copos e Canecas', 17.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/07392-1-v1.jpg', NULL, '[{"n": "Inox", "h": "#B8BCC4"}]'::jsonb, false, 24),
  ('13282', 'Caneca Cerâmica 330Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Canecas', 'copos-e-canecas', 'Copos e Canecas', 23.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13282-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13282-2-v1.jpg', '[{"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 25),
  ('04070', 'Caneca Térmica 700Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Canecas', 'copos-e-canecas', 'Copos e Canecas', 74.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04070-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/04070/04070_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Azul Escuro", "h": "#1E3A5F"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 26),
  ('03590', 'Caneca Inox 370Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Canecas', 'copos-e-canecas', 'Copos e Canecas', 28.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03590-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03590-2-v1.jpg', '[{"n": "Laranja", "h": "#F97316"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Azul", "h": "#3B82F6"}]'::jsonb, false, 27),
  ('18912', 'Caneca Térmica Inox 300Ml', 'COPOS, GARRAFAS E CANECAS', 'Copos, Garrafas e Canecas', 'Canecas', 'copos-e-canecas', 'Copos e Canecas', 61.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18912-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/18912/18912_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}]'::jsonb, false, 28),
  ('01320', 'Mochila De Nylon Usb 20L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Mochilas e Sacochilas', 'mochilas', 'Mochilas', 91.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01320-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/01320/01320_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Preto", "h": "#111827"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 29),
  ('18539', 'Mochila De Nylon Dobrável 21L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Mochilas e Sacochilas', 'mochilas', 'Mochilas', 37.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18539-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18539-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Cinza", "h": "#6B7280"}]'::jsonb, false, 30),
  ('02105', 'Mochila Nylon 17L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Mochilas e Sacochilas', 'mochilas', 'Mochilas', 52.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02105-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02105-2-v1.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Preto", "h": "#111827"}, {"n": "Prata", "h": "#C0C0C0"}]'::jsonb, false, 31),
  ('02066', 'Mochila Nylon Poliester', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Mochilas e Sacochilas', 'mochilas', 'Mochilas', 162.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02066-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 32),
  ('18601', 'Sacochila Poliéster', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Mochilas e Sacochilas', 'mochilas', 'Mochilas', 27.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18601-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/18601/18601_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Azul Escuro", "h": "#1E3A5F"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 33),
  ('01326', 'Mochila De Nylon Usb 20L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Mochilas e Sacochilas', 'mochilas', 'Mochilas', 91.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01326-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01326-2-v1.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Prata", "h": "#C0C0C0"}]'::jsonb, false, 34),
  ('06024', 'Bolsa Térmica 6L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Bolsas Térmicas', 'bolsas-termicas', 'Bolsas Térmicas', 27.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06024-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06024-2-v2.jpg', '[{"n": "Rosa", "h": "#EC4899"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}, {"n": "Bege", "h": "#E8D9BE"}, {"n": "Cinza", "h": "#6B7280"}]'::jsonb, false, 35),
  ('04357', 'Bolsa Térmica 10L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Bolsas Térmicas', 'bolsas-termicas', 'Bolsas Térmicas', 62.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04357-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04357-2-v2.jpg', '[{"n": "Cinza", "h": "#6B7280"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 36),
  ('02596', 'Bolsa Térmica 15L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Bolsas Térmicas', 'bolsas-termicas', 'Bolsas Térmicas', 31.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02596-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/02596/02596_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 37),
  ('02399', 'Bolsa Térmica 6 Litros.', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Bolsas Térmicas', 'bolsas-termicas', 'Bolsas Térmicas', 15.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02399-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02399-2-v1.jpg', '[{"n": "Cinza", "h": "#6B7280"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Preto", "h": "#111827"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Azul", "h": "#3B82F6"}]'::jsonb, false, 38),
  ('02697', 'Bolsa Térmica 17L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Bolsas Térmicas', 'bolsas-termicas', 'Bolsas Térmicas', 20.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02697-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02697-2-v1.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}, {"n": "Cinza", "h": "#6B7280"}]'::jsonb, false, 39),
  ('04385', 'Bolsa Térmica 11L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Bolsas Térmicas', 'bolsas-termicas', 'Bolsas Térmicas', 72.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04385-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04385-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Cinza", "h": "#6B7280"}]'::jsonb, false, 40),
  ('06070P', 'Mala De Bordo 30 Litros', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Malas de Viagem', 'malas-de-viagem', 'Malas de Viagem', 417.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06070P-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 41),
  ('15436', 'Balança De Mala', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Malas de Viagem', 'malas-de-viagem', 'Malas de Viagem', 49.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/15436-1-v1.jpg', NULL, '[{"n": "Inox", "h": "#B8BCC4"}]'::jsonb, false, 42),
  ('08242', 'Mala De Viagem 37L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Malas de Viagem', 'malas-de-viagem', 'Malas de Viagem', 375.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08242-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08242-2-v2.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 43),
  ('06068', 'Mala De Viagem 66L', 'MOCHILAS, BOLSAS TÉRMICAS E MALAS', 'Mochilas, Bolsas e Malas', 'Malas de Viagem', 'malas-de-viagem', 'Malas de Viagem', 412.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06068-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06068-2-v1.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Chumbo", "h": "#4B5563"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Rosa", "h": "#EC4899"}]'::jsonb, false, 44),
  ('18516', 'Necessaire Em Poliester Impermeável', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Necessaires', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 8.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18516-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/18516/18516_2.jpg', '[{"n": "Azul Claro", "h": "#60A5FA"}, {"n": "Azul Escuro", "h": "#1E3A5F"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa Claro", "h": "#F9A8D4"}, {"n": "Rosa Escuro", "h": "#BE185D"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Turquesa", "h": "#14B8A6"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 45),
  ('18501', 'Nécessaire De Nylon', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Necessaires', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 21.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18501-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/18501/18501_2.jpg', '[{"n": "Azul Claro", "h": "#60A5FA"}, {"n": "Azul Escuro", "h": "#1E3A5F"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 46),
  ('18738', 'Nécessaire Poliéster', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Necessaires', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 24.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18738-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18738-2-v1.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Preto", "h": "#111827"}, {"n": "Marrom", "h": "#92400E"}]'::jsonb, false, 47),
  ('01228P', 'Necessaire Pvc Impermeável C/ Plaquinha', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Necessaires', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 27.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01228P-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01228P-2-v1.jpg', '[{"n": "Rosa", "h": "#EC4899"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 48),
  ('18753', 'Nécessaire De Poliéster', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Necessaires', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 47.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18753-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18753-2-v2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 49),
  ('01622B', 'Porta Joias', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Porta Joias', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 20.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01622B-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01622B-2-v1.jpg', '[{"n": "Rosa", "h": "#EC4899"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Bege", "h": "#E8D9BE"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 50),
  ('08142', 'Porta-Joias Com Espelho', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Porta Joias', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 27.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08142-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08142-2-v2.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Bege", "h": "#E8D9BE"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 51),
  ('18717', 'Porta Joias', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Porta Joias', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 84.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18717-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18717-2-v1.jpg', '[{"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Laranja", "h": "#F97316"}]'::jsonb, false, 52),
  ('01361B', 'Kit Manicure 7 Peças', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Kit Manicure', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 17.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01361B-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 53),
  ('18724', 'Kit Manicure 16 Peças', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Kit Manicure', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 37.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18724-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18724-2-v1.jpg', '[{"n": "Verde", "h": "#22C55E"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}]'::jsonb, false, 54),
  ('18900', 'Kit Manicure 10 Peças', 'NECESSAIRES, PORTA JOIAS E KIT MANICURE', 'Necessaires e Porta Joias', 'Kit Manicure', 'necessaires-e-porta-joias', 'Necessaires e Porta Joias', 33.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18900-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18900-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Marrom", "h": "#92400E"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Rosa", "h": "#EC4899"}]'::jsonb, false, 55),
  ('03009', 'Caderneta Emborrachada', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Cadernetas', 'cadernetas', 'Cadernetas', 10.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03009-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03009-2-v1.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Preto", "h": "#111827"}, {"n": "Marrom", "h": "#92400E"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 56),
  ('05067', 'Caderneta Emborrachada', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Cadernetas', 'cadernetas', 'Cadernetas', 17.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05067-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05067-2-v1.jpg', '[{"n": "Verde", "h": "#22C55E"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Preto", "h": "#111827"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Bege", "h": "#E8D9BE"}]'::jsonb, false, 57),
  ('03005', 'Caderneta De Couro Sintético', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Cadernetas', 'cadernetas', 'Cadernetas', 18.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03005-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03005-2-v1.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Preto", "h": "#111827"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Marrom", "h": "#92400E"}]'::jsonb, false, 58),
  ('14092N', 'Caderneta Emborrachada Com Porta Caneta', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Cadernetas', 'cadernetas', 'Cadernetas', 28.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/14092N-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/14092N-2-v1.jpg', '[{"n": "Rosa", "h": "#EC4899"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Amarelo", "h": "#EAB308"}, {"n": "Preto", "h": "#111827"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Cinza", "h": "#6B7280"}]'::jsonb, false, 59),
  ('05071', 'Caderno A5 Plástico', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Cadernetas', 'cadernetas', 'Cadernetas', 12.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05071-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/05071/05071_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Bege", "h": "#E8D9BE"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Marrom", "h": "#92400E"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde Claro", "h": "#4ADE80"}, {"n": "Verde Escuro", "h": "#166534"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Vinho", "h": "#7F1D1D"}]'::jsonb, false, 60),
  ('11911S', 'Bloco De Anotações C/ Auto-Adesivo', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Blocos de Anotações', 'cadernetas', 'Cadernetas', 8.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/11911S-1-v1.jpg', NULL, '[{"n": "Kraft", "h": "#C8A87C"}]'::jsonb, false, 61),
  ('05065', 'Bloco De Anotações C/ Auto Adesivos', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Blocos de Anotações', 'cadernetas', 'Cadernetas', 11.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05065-1-v1.jpg', NULL, '[{"n": "Kraft", "h": "#C8A87C"}]'::jsonb, false, 62),
  ('06098', 'Bloco De Anotações Com Caneta', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Blocos de Anotações', 'cadernetas', 'Cadernetas', 14.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06098-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06098-2-v1.jpg', '[{"n": "Bege", "h": "#E8D9BE"}]'::jsonb, false, 63),
  ('05064', 'Bloco De Anotações Ecológico Com Caneta', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Blocos de Anotações', 'cadernetas', 'Cadernetas', 10.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05064-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05064-2-v2.jpg', '[{"n": "Bege", "h": "#E8D9BE"}, {"n": "Marrom", "h": "#92400E"}]'::jsonb, false, 64),
  ('12638', 'Caneta Plástica Touch', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Canetas', 'canetas', 'Canetas', 2.20, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/12638-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/12638-2-v1.jpg', '[{"n": "Branco", "h": "#F9FAFB"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Prata", "h": "#C0C0C0"}]'::jsonb, false, 65),
  ('ER143B', 'Caneta Metal', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Canetas', 'canetas', 'Canetas', 3.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/ER143B-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/ER143B/ER143B_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Azul Claro", "h": "#60A5FA"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Branco Perola", "h": "#F3EFE7"}, {"n": "Champagne", "h": "#E3D3B0"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Cromado", "h": "#CBD0D6"}, {"n": "Dourado", "h": "#D4A15A"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Vinho", "h": "#7F1D1D"}]'::jsonb, false, 66),
  ('13546B', 'Caneta C/ 1 Anel E Ponta Touch', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Canetas', 'canetas', 'Canetas', 4.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13546B-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13546B-2-v2.jpg', '[{"n": "Branco", "h": "#F9FAFB"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Amarelo", "h": "#EAB308"}, {"n": "Dourado", "h": "#D4A15A"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 67),
  ('13499B', 'Caneta Plastica C/ Suporte E Touch', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Canetas', 'canetas', 'Canetas', 3.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13499B-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13499B-2-v1.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Preto", "h": "#111827"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 68),
  ('05015B', 'Caneta Metal Touch', 'CADERNETAS, AGENDAS, BLOCOS E CANETAS', 'Cadernetas, Blocos e Canetas', 'Canetas', 'canetas', 'Canetas', 5.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05015B-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05015B-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Chumbo", "h": "#4B5563"}, {"n": "Cinza", "h": "#6B7280"}]'::jsonb, false, 69),
  ('09824', 'Chaveiro Metal Abridor', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Chaveiros', 'chaveiros', 'Chaveiros', 2.07, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/09824-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/09824-2-v1.jpg', '[{"n": "Verde", "h": "#22C55E"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Dourado", "h": "#D4A15A"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Cobre", "h": "#B87333"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 70),
  ('01955', 'Chaveiro Metal Retangular', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Chaveiros', 'chaveiros', 'Chaveiros', 7.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01955-1-v1.jpg', NULL, '[{"n": "Prata", "h": "#C0C0C0"}]'::jsonb, false, 71),
  ('08232', 'Chaveiro Trena Plástico 2 Metros', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Chaveiros', 'chaveiros', 'Chaveiros', 5.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08232-1-v1.jpg', NULL, '[{"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 72),
  ('01812', 'Mouse Pad', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Mouse Pad', 'mouse-pad', 'Mouse Pad', 4.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01812-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01812-2-v2.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 73),
  ('03007', 'Mouse Pad Ergonômico', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Mouse Pad', 'mouse-pad', 'Mouse Pad', 11.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03007-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03007-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}]'::jsonb, false, 74),
  ('01810', 'Mouse Pad C/ Almofada', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Mouse Pad', 'mouse-pad', 'Mouse Pad', 21.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01810-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01810-2-v1.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Amarelo", "h": "#EAB308"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Roxo", "h": "#8B5CF6"}]'::jsonb, false, 75),
  ('01810A', 'Mouse Pad Ergonômico', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Mouse Pad', 'mouse-pad', 'Mouse Pad', 21.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01810A-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 76),
  ('07048B', 'Kit Executivo Ecológico 3 Peças', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Kit Executivo', 'kit-executivo', 'Kit Executivo', 54.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/07048B-1-v1.jpg', NULL, '[{"n": "Bambu", "h": "#C9A26B"}]'::jsonb, false, 77),
  ('08254', 'Kit Executivo 2 Peças', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Kit Executivo', 'kit-executivo', 'Kit Executivo', 67.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08254-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 78),
  ('19029', 'Kit Executivo 2 Peças', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Kit Executivo', 'kit-executivo', 'Kit Executivo', 27.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/19029-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/19029/19029_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 79),
  ('08255', 'Kit Executivo 2 Peças', 'CHAVEIROS, MOUSE PAD E KIT EXECUTIVO', 'Chaveiros, Mouse Pad e Kit Executivo', 'Kit Executivo', 'kit-executivo', 'Kit Executivo', 87.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08255-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 80),
  ('04067', 'Caixa De Som Com Luminária', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Caixas de Som', 'som-e-power-bank', 'Som e Power Bank', 67.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04067-1-v1.jpg', NULL, '[{"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 81),
  ('04362', 'Caixa De Som Multimídia', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Caixas de Som', 'som-e-power-bank', 'Som e Power Bank', 112.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04362-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04362-2-v1.jpg', '[{"n": "Chumbo", "h": "#4B5563"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 82),
  ('08002', 'Caixa De Som Bluetooth Tws', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Caixas de Som', 'som-e-power-bank', 'Som e Power Bank', 42.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08002-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/08002/08002_2.jpg', '[{"n": "Dourado", "h": "#D4A15A"}, {"n": "Pink", "h": "#DB2777"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Preto", "h": "#111827"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 83),
  ('06093', 'Caixa De Som Com Carregador Indução', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Caixas de Som', 'som-e-power-bank', 'Som e Power Bank', 119.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06093-1-v1.jpg', NULL, '[{"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 84),
  ('04065', 'Caixa De Som Multimídia Com Relógio', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Caixas de Som', 'som-e-power-bank', 'Som e Power Bank', 79.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04065-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 85),
  ('12789', 'Fone De Ouvido C/ Microfone -Bco/Bco', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Fones de Ouvido', 'som-e-power-bank', 'Som e Power Bank', 12.48, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/12789-1-v1.jpg', NULL, '[{"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 86),
  ('05021', 'Fone Bluetooth C/ Carregador', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Fones de Ouvido', 'som-e-power-bank', 'Som e Power Bank', 49.97, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05021-1-v1.jpg', NULL, '[{"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 87),
  ('06064', 'Fone De Ouvido Bluetooth Touch Com Case Carregador', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Fones de Ouvido', 'som-e-power-bank', 'Som e Power Bank', 54.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06064-1-v1.jpg', NULL, '[{"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 88),
  ('05048', 'Fone De Ouvido Bluetooth', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Fones de Ouvido', 'som-e-power-bank', 'Som e Power Bank', 49.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05048-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 89),
  ('06052', 'Power Bank 10.000Mah Com Carregamento Via Indução Ou Via Cabo', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Power Banks', 'som-e-power-bank', 'Som e Power Bank', 154.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06052-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/06052/06052_2.jpg', '[{"n": "Branco", "h": "#F9FAFB"}, {"n": "Branco Com Cinza", "h": ["#F9FAFB", "#6B7280"]}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 90),
  ('09145', 'Power Bank 10.000Mah Com Carregamento Via Indução Ou Via Cabo', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Power Banks', 'som-e-power-bank', 'Som e Power Bank', 137.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/09145-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/09145-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 91),
  ('08188', 'Power Bank 10.000Mah Com Indicador Led', 'CAIXAS DE SOM, FONES E POWER BANK', 'Som, Fones e Power Bank', 'Power Banks', 'som-e-power-bank', 'Som e Power Bank', 137.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08188-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/08188-2-v1.jpg', '[{"n": "Branco", "h": "#F9FAFB"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 92),
  ('18537G', 'Sacola Em Tnt Revestida C/ Plastico', 'SACOLA DE ALGODÃO E TNT', 'Sacolas de Algodão e TNT', 'Sacolas de Algodão e TNT', 'sacolas', 'Sacolas', 11.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18537G-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18537G-2-v2.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Prata", "h": "#C0C0C0"}, {"n": "Cobre", "h": "#B87333"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Dourado", "h": "#D4A15A"}]'::jsonb, false, 93),
  ('13780', 'Sacola Tnt Com Alça', 'SACOLA DE ALGODÃO E TNT', 'Sacolas de Algodão e TNT', 'Sacolas de Algodão e TNT', 'sacolas', 'Sacolas', 4.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13780-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13780-2-v1.jpg', '[{"n": "Preto", "h": "#111827"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}]'::jsonb, false, 94),
  ('13803N', 'Sacola De Algodão', 'SACOLA DE ALGODÃO E TNT', 'Sacolas de Algodão e TNT', 'Sacolas de Algodão e TNT', 'sacolas', 'Sacolas', 12.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13803N-1-v1.jpg', NULL, '[{"n": "Bege", "h": "#E8D9BE"}]'::jsonb, false, 95),
  ('18537P', 'Sacola Em Tnt Revestida C/ Plastico', 'SACOLA DE ALGODÃO E TNT', 'Sacolas de Algodão e TNT', 'Sacolas de Algodão e TNT', 'sacolas', 'Sacolas', 9.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18537P-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18537P-2-v1.jpg', '[{"n": "Vermelho", "h": "#EF4444"}, {"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Cobre", "h": "#B87333"}, {"n": "Dourado", "h": "#D4A15A"}, {"n": "Prata", "h": "#C0C0C0"}]'::jsonb, false, 96),
  ('13781N', 'Sacola De Tnt', 'SACOLA DE ALGODÃO E TNT', 'Sacolas de Algodão e TNT', 'Sacolas de Algodão e TNT', 'sacolas', 'Sacolas', 2.88, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13781N-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/13781N-2-v1.jpg', '[{"n": "Branco", "h": "#F9FAFB"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Cinza", "h": "#6B7280"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Bege", "h": "#E8D9BE"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Amarelo", "h": "#EAB308"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 97),
  ('04399', 'Sacola De Algodão', 'SACOLA DE ALGODÃO E TNT', 'Sacolas de Algodão e TNT', 'Sacolas de Algodão e TNT', 'sacolas', 'Sacolas', 18.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/04399-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/04399/04399_2.jpg', '[{"n": "Bege", "h": "#E8D9BE"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 98),
  ('07447', 'Kit Churrasco No Estojo C/ 2 Pçs', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Churrasco', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 42.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/07447-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/07447/07447_2.jpg', '[{"n": "Madeira", "h": "#B98B57"}]'::jsonb, false, 99),
  ('01644', 'Kit Churrasco Na Maleta 4 Peças', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Churrasco', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 137.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/01644-1-v1.jpg', NULL, '[{"n": "Prata", "h": "#C0C0C0"}]'::jsonb, false, 100),
  ('02250', 'Kit Churrasco 5 Peças', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Churrasco', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 112.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02250-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 101),
  ('18891', 'Kit Churrasco 3 Peças', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Churrasco', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 74.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18891-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/18891/18891_2.jpg', '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 102),
  ('05184B', 'Kit Churrasco 8 Peças', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Churrasco', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 118.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05184B-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 103),
  ('18621', 'Saca Rolhas', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Vinho', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 9.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18621-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18621-2-v2.jpg', '[{"n": "Amarelo", "h": "#EAB308"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 104),
  ('10071G', 'Kit Vinho Caixa De Papelão 2 Peças', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Vinho', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 33.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/10071G-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 105),
  ('03493', 'Kit Vinho P/ 1 Garrafa', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Vinho', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 94.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/03493-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 106),
  ('11871', 'Kit Vinho Plástico Resistente 3 Peças Formato Garrafa', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Vinho', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 52.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/11871-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/11871/11871_2.jpg', '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 107),
  ('11870', 'Kit Vinho 5Pçs Formato Garrafa', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Vinho', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 62.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/11870-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 108),
  ('12046', 'Kit Vinho Xadrez 4 Pçs', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Vinho', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 87.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/12046-1-v1.jpg', NULL, '[{"n": "Preto", "h": "#111827"}]'::jsonb, false, 109),
  ('10695', 'Saca Rolhas Metálico', 'KIT CHURRASCO E KIT VINHO', 'Kit Churrasco e Kit Vinho', 'Kit Vinho', 'kit-vinho-e-churrasco', 'Kit Vinho e Churrasco', 10.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/10695-1-v1.jpg', NULL, '[{"n": "Prata", "h": "#C0C0C0"}]'::jsonb, false, 110),
  ('06090', 'Marmita Dupla Fibra Bambu', 'MARMITAS E TÁBUAS DE MADEIRA', 'Marmitas e Tábuas', 'Marmitas', 'marmitas', 'Marmitas', 37.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06090-1-v1.jpg', NULL, '[{"n": "Bege", "h": "#E8D9BE"}]'::jsonb, false, 111),
  ('06089', 'Marmita Fibra Trigo', 'MARMITAS E TÁBUAS DE MADEIRA', 'Marmitas e Tábuas', 'Marmitas', 'marmitas', 'Marmitas', 29.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06089-1-v1.jpg', NULL, '[{"n": "Bege", "h": "#E8D9BE"}]'::jsonb, false, 112),
  ('18857', 'Marmita Hermética De Palha De Trigo', 'MARMITAS E TÁBUAS DE MADEIRA', 'Marmitas e Tábuas', 'Marmitas', 'marmitas', 'Marmitas', 26.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18857-1-v1.jpg', NULL, '[{"n": "Bege", "h": "#E8D9BE"}]'::jsonb, false, 113),
  ('18858', 'Marmita Hermética Plástica 1L', 'MARMITAS E TÁBUAS DE MADEIRA', 'Marmitas e Tábuas', 'Marmitas', 'marmitas', 'Marmitas', 34.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18858-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18858-2-v2.jpg', '[{"n": "Marrom", "h": "#92400E"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Bege", "h": "#E8D9BE"}]'::jsonb, false, 114),
  ('18584B', 'Tábua De Corte Com Canaleta', 'MARMITAS E TÁBUAS DE MADEIRA', 'Marmitas e Tábuas', 'Tábuas e Petisqueiras', 'tabuas', 'Tábuas', 22.50, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18584B-1-v1.jpg', NULL, '[{"n": "Bambu", "h": "#C9A26B"}]'::jsonb, false, 115),
  ('18591B', 'Tábua De Corte Com Canaleta', 'MARMITAS E TÁBUAS DE MADEIRA', 'Marmitas e Tábuas', 'Tábuas e Petisqueiras', 'tabuas', 'Tábuas', 24.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18591B-1-v1.jpg', NULL, '[{"n": "Madeira", "h": "#B98B57"}]'::jsonb, false, 116),
  ('18599', 'Tábua De Corte Com Canaleta 34X24', 'MARMITAS E TÁBUAS DE MADEIRA', 'Marmitas e Tábuas', 'Tábuas e Petisqueiras', 'tabuas', 'Tábuas', 34.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18599-1-v1.jpg', NULL, '[{"n": "Madeira", "h": "#B98B57"}]'::jsonb, false, 117),
  ('18629', 'Kit Queijo 2 Peças + Tábua Redonda', 'MARMITAS E TÁBUAS DE MADEIRA', 'Marmitas e Tábuas', 'Tábuas e Petisqueiras', 'tabuas', 'Tábuas', 78.00, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/18629-1-v1.jpg', NULL, '[{"n": "Madeira", "h": "#B98B57"}]'::jsonb, false, 118),
  ('02075', 'Guarda-Chuva', 'GUARDA-CHUVAS', 'Guarda-Chuvas', 'Guarda-Chuvas', 'guarda-chuvas', 'Guarda-Chuvas', 33.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02075-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/02075/02075_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}, {"n": "Vermelho", "h": "#EF4444"}]'::jsonb, false, 119),
  ('05198', 'Guarda-Chuva Manual', 'GUARDA-CHUVAS', 'Guarda-Chuvas', 'Guarda-Chuvas', 'guarda-chuvas', 'Guarda-Chuvas', 24.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05198-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/05198/05198_2.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Azul Escuro", "h": "#1E3A5F"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vinho", "h": "#7F1D1D"}]'::jsonb, false, 120),
  ('05044', 'Guarda-Chuva Automático', 'GUARDA-CHUVAS', 'Guarda-Chuvas', 'Guarda-Chuvas', 'guarda-chuvas', 'Guarda-Chuvas', 51.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05044-1-v2.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05044-2-v1.jpg', '[{"n": "Laranja", "h": "#F97316"}, {"n": "Marrom", "h": "#92400E"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Azul", "h": "#3B82F6"}, {"n": "Roxo", "h": "#8B5CF6"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Rosa", "h": "#EC4899"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 121),
  ('02078', 'Guarda-Chuva Invertido', 'GUARDA-CHUVAS', 'Guarda-Chuvas', 'Guarda-Chuvas', 'guarda-chuvas', 'Guarda-Chuvas', 73.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02078-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/02078-2-v1.jpg', '[{"n": "Azul", "h": "#3B82F6"}, {"n": "Branco", "h": "#F9FAFB"}, {"n": "Preto", "h": "#111827"}]'::jsonb, false, 122),
  ('05045', 'Guarda-Chuva Manual Com Proteção Uv', 'GUARDA-CHUVAS', 'Guarda-Chuvas', 'Guarda-Chuvas', 'guarda-chuvas', 'Guarda-Chuvas', 50.75, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/05045-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/site-images/topprodutos/05045/05045_2.jpg', '[{"n": "Azul Claro", "h": "#60A5FA"}, {"n": "Azul Escuro", "h": "#1E3A5F"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}, {"n": "Verde", "h": "#22C55E"}]'::jsonb, false, 123),
  ('06063', 'Guarda-Chuva Automático', 'GUARDA-CHUVAS', 'Guarda-Chuvas', 'Guarda-Chuvas', 'guarda-chuvas', 'Guarda-Chuvas', 52.25, 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06063-1-v1.jpg', 'https://ozkbfxvouxgsdthnweyr.supabase.co/storage/v1/object/public/catalogo-meta/06063-2-v1.jpg', '[{"n": "Branco", "h": "#F9FAFB"}, {"n": "Verde", "h": "#22C55E"}, {"n": "Vermelho", "h": "#EF4444"}, {"n": "Laranja", "h": "#F97316"}, {"n": "Preto", "h": "#111827"}, {"n": "Azul", "h": "#3B82F6"}]'::jsonb, false, 124)
ON CONFLICT (codigo) DO NOTHING;
